### ISSUE TITLE
Implement HyperAttention -  Long-context Attention in Near-Linear Time: outperforms FlashAttention and offers up to 5x speedup on long contexts

### ISSUE THREAD

**Issue by kabachuha** [turboderp/exllamav2#115]
The research by Google was released on 11 Oct 2023 https://arxiv.org/pdf/2310.05869.pdf

**Comment by Ph0rk0z** [comment]
There is also flash decoding. Inside flash-attention already.

**Comment by turboderp** [comment]
Yeah I'm skeptical of jumping on every new idea that comes out. HyperAttention is an approximation of dot-product attention, and according to their own tests it has very measurable impact on pretrained models. And the performance gain is only for attention, which isn't really the main bottleneck in ExLlama.

I do need to look into Flash Decoding, to see what it actually takes to trigger it, or if it's used automatically or what. There's not a huge performance jump from flath-attn 2.2.1 to 2.3.0 at least, so if it only works with the decoder module defined by flash-attn, it's a non-starter since that wouldn't support quantization.

**Comment by Ph0rk0z** [comment]
Maybe it's possible to ask him to make it stand alone and not just for the decoder module.

**Comment by ChuanhongLi** [comment]
> Yeah I'm skeptical of jumping on every new idea that comes out. HyperAttention is an approximation of dot-product attention, and according to their own tests it has very measurable impact on pretrained models. And the performance gain is only for attention, which isn't really the main bottleneck in ExLlama.
> 
> I do need to look into Flash Decoding, to see what it actually takes to trigger it, or if it's used automatically or what. There's not a huge performance jump from flath-attn 2.2.1 to 2.3.0 at least, so if it only works with the decoder module defined by flash-attn, it's a non-starter since that wouldn't support quantization.

@turboderp Hi, do you have a answer whether flash-decoding is triggered automatically when using flash-attn(2.3.2) or we need do something else? 
I see in exllama v1, attn_output = flash_attn_func(query_states, key_states, value_states, causal = (past_len == 0)), but not very clear whether flash-decoding is used or not.
