### ISSUE TITLE
gpu_split does not seem to work for me

### ISSUE THREAD

**Issue by S-Yacer** [turboderp/exllamav2#116]
gpu_split is set to "80,  80, 80 , 80" but is only using a single gpu (cuda:0). 

class method code:
```
 @classmethod
    def from_pretrained(cls, path_to_model, model_dir, max_seq_len, compress_pos_emb, alpha_value, gpu_split=None):
        # Removed unrelated code
        if gpu_split:
            split = [float(alloc) for alloc in gpu_split.split(",")]

        model.load(split)
```

terminal output: `RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.`

**Comment by turboderp** [comment]
The GPU split defines how much space to allocate for weights and buffers on each device but specifically excludes the cache, since the cache is allocated separately and can be any size depending on what you're doing with the model. You can also have multiple caches, and now 8-bit caches, etc.

So overall, if you have 4 x 80GB GPUs, you'll probably want a split along the lines of [70,70,70,70], or something. I would try that, or maybe less, and then check the output of `nvidia-smi` to see how much memory you actually end up using with the cache, and then dial it in that way.

I do wonder what model you're using that needs 320 GB of VRAM, though?

**Comment by S-Yacer** [comment]
Thanks for the response. To answer your question, I am trying to load multiple models but the workload doesn't split across the gpus, it does everything on a single GPU... even though I am defining gpu_split to be [70,70,70,70] for e.g.

**Comment by turboderp** [comment]
If you load the first model with a split of [1,2,3,4], that means it will place 1 GB of weights+buffers on the first GPU, 2 GB on the second, and so on. If you load another model with that same split, it will *also* try to use 1 GB on the first GPU, 2 GB on the second etc. There's no accounting of how much VRAM is used between calls to `ExLlamaV2.load()` and it doesn't consider how much is currently available.

If you call `ExLlamaV2.load()` with `stats = True`, it will return a tuple of gpu_split (what you passed) and a list of how much of that allocation wasn't used up. So essentially you could do:

```python
gpu_split = [70,70,70,70]  # initial split
for model in models:
    _, gpu_split = model.load(gpu_split, stats = True)  # returns e.g. [70,70,70,70], [42.1,70,70,70]
```

This isn't a perfect solution because caches aren't accounted for, and how much cache space you'll need on a device depends which particular models end up on that device and what parameters you choose for each cache. Each layer of the cache must reside on the same device as the attention block it is tied to, but not all layers are attention blocks, so depending on exactly where the model ends up getting split you may need a little more or a little less VRAM for the cache on any given device.

Also, some of the memory *reserved* when loading a model isn't permanently allocated. E.g. attention weights only exist in VRAM during the attention step, so that memory could be shared between two models on the same device.

**Comment by S-Yacer** [comment]
Solved, thank you
