### ISSUE TITLE
Suggestion: allow different context lengths for draft model and main model in speculative sampling

### ISSUE THREAD

**Issue by Antollo** [turboderp/exllamav2#149]
I tried using speculative sampling with Llama 2 70b as the main model and TinyLlama 1.1b as the draft model. Max context length of TinyLlama is 2048, and it limits max context length of the whole approach. My suggestion is to use last `k` (new parameter for sampler) tokens for the draft model.

**Comment by turboderp** [comment]
It's tough, because then you'd have to manage the context of the draft model separately. Every generation would start with prefilling the cache for the draft model, which negates some or potentially all of the benefits.
 
Here's what I do in the chatbot example:

```python
    if draft_config.max_seq_len < model.config.max_seq_len:

        if args.no_draft_scale:
            print(f" !! Warning: Draft model native max sequence length is less than sequence length for model. Speed may decrease after {draft_config.max_seq_len} tokens.")
        else:
            ratio = model.config.max_seq_len / draft_config.max_seq_len
            alpha = -0.13436 + 0.80541 * ratio + 0.28833 * ratio ** 2
            draft_config.scale_alpha_value = alpha
            print(f" -- Applying draft model RoPE alpha = {alpha:.4f}")

    draft_config.max_seq_len = model.config.max_seq_len
```

It forces the draft model's sequence length to be the same as the full model and then by default applies NTK alpha scaling using a magic formula to get the alpha value. This obviously degrades the draft model somewhat if you're scaling it from 2k to 16k or something, but it still seems to perform decently in my tests. Of course, truncating the draft model's past would have a similar effect of making it less accurate and I'm not sure which would be worse. But at any rate the draft doesn't have to be *great*, it just has to be "somewhat useful."

**Comment by Antollo** [comment]
That makes sense. I tested using draft model with NTK scaling applied on long context (appox. 3800 tokens). Without flash-attention the boost is quite impressive (from approx. 11 t/s to 15 t/s) and with flash-attention it's less noticeable (from 19 t/s to 22 t/s).

**Comment by turboderp** [comment]
It will depend on what you're generating and also on sampling settings. The draft model is sampled greedily, so the higher your temperature, top-P etc. is, the more likely you are to deviate from the draft.

There are ways to possibly improve on that by drafting recursively, but it would conflict with how Flash Attention applies attention masks, so I don't know if it's worth pursuing.

**Comment by gabinguo** [comment]
@turboderp Hi! I would like to ask about the source of the magic formula you mentioned. Is it derived from established literature, or is it based on your empirical experience?
