### ISSUE TITLE
Lower bits per weight

### ISSUE THREAD

**Issue by IgnacioFDM** [turboderp/exllamav2#2]
In the readme you mention
> In my tests, this scheme allows Llama2 70B to run on a single 24 GB GPU with a 2048-token context, producing coherent and mostly stable output with 2.55 bits per weight. 13B models run at 2.65 bits within 8 GB of VRAM, although currently none of them uses GQA which effectively limits the context size to 2048. In either case it's unlikely that the model will fit alongside a desktop environment. For now.

Have you done any testing with slightly lower bits per weight, so as to fit it alongside a DE? Have you found any breaking point where the model becomes incoherent or the degradation is just too much?

**Comment by turboderp** [comment]
I've been working on it. I definitely consider it a milestone to get 70B running comfortably in 24 GB for 3090/4090 users with a single GPU. And it's close, but it's also slow progress, since quantizing a model that big can take several hours, and you'll end up doing it *many* times over trying out various different things.

The difference in perplexity between 2.5 and 2.55 bits is huge, but 2.5 is still coherent and gives an extra 350 MB of headroom or so. Although, at 2.5 bits the model does start to freak out whenever it sees the word "Auchtermuchty". And 2.5 bits still isn't quite small enough, anyway. But I have some ideas I'm going to be trying out soon, so stay tuned.

**Comment by IgnacioFDM** [comment]
Awesome. Great work.

An idea (that you've probably already considered) is doing a small pruning (5% - 10%) before the quantization. And if the pruning targets outlier weights maybe it could also help with later quantization errors.

**Comment by BarfingLemurs** [comment]
@IgnacioFDM One possibility for longer context/desktop experience is with nvidia's shared memory with recent windows drivers. But that sucks

**Comment by turboderp** [comment]
I've been doing more quants and I'm currently uploading new versions of 70B-chat, down to 2.3 bits per weight. At that size you can fit a 4k context on a 24 GB alongside a desktop environment just barely, or you can go down to 2k context for a little more headroom. Here it is running on my 4090 alongside a desktop environment, with lots of other running at the same time:

![Screenshot_20230917_135459](https://github.com/turboderp/exllamav2/assets/11859846/e0207298-6bb1-45b5-9dca-fb03d76ccbbc)

**Comment by IgnacioFDM** [comment]
Awesome. I'll give it a try later. Is this the same method as before but with a 2.3 setting, or does it contain new improvements?

**Comment by turboderp** [comment]
Well, the new models are currently uploading and it looks like it will take a while... zz...

But once they're done, it's a new quant with the same method, I've just added a bunch more variants to the measurement pass, added some safeguards in the quantizer to prevent FP16 overflows in places, added sharding, improved precision in the kernels, and more. The old models are still compatible, the new ones are just better, hence why it works down to 2.3 bits now. There's also flash-attn support and more.

**Comment by QM60** [comment]
Is it feasible to make an even smaller BPW option for layers? I think right now the lowest is ~2.17bpw, which leaves barely any wiggle room for the optimizer at these levels. At a target of 2.3, there's very few "free bits" to allocate to the most important layers.
I can't believe I'm seriously contemplating 1bit, but who knows? Perhaps it's starting to blur between pruning and quantization at that point, but sacrifices might need to be made.

**Comment by turboderp** [comment]
Problem with going below 2 bits is that with a "simple" quantization scheme is that then you're at a single bit, and you've only got two points on the quantization grid. And you lose a lot if you can't represent "positive", "negative" and "zero" within the same group.

I did try early on using quantized low-rank approximations, going effectively well below 1 bit per weight. But while it works for a few layers, those are also layers that already quantize very easily to 2 bits, so there isn't much to gain from it, while there's a lot of added complexity and potential problems (judging the actual damage caused by quantization or any other related technique is non-trivial.)

I have other ideas for novel compression/quantization schemes that I hope to have some time to experiment with soon, but there is a limit to how far you can realistically expect to get without compute-heavy techniques like distillation.

**Comment by IgnacioFDM** [comment]
Did you manage to upload the model? I don't see it in your HF, maybe you left it as private?

**Comment by turboderp** [comment]
It is uploaded now, finally. [Here](https://huggingface.co/turboderp/Llama2-70B-chat-exl2)

**Comment by turboderp** [comment]
It's hard to say. It may be a problem with ooba or an old version of the quant. Could be weird sampling parameters as well, hard to say from just one screenshot. The model can definitely produce coherent text:

![Screenshot_20231005_111822](https://github.com/turboderp/exllamav2/assets/11859846/a3a4f35b-473e-4b50-aac5-ee55575b0685)

I guess I'll need to do some work testing it on TGW.. hm.

**Comment by alkeryn** [comment]
thanks !
maybe it's an issue with ooba.

**Comment by turboderp** [comment]
I've been experimenting a bit, and ooba seems to work with the 2.5-bit quant of the Llama2-70B base model. I've seen that exact output from the screenshot above ("Cord Cord StringBuilder...") and it seems to happen only with some particular finetuned models, and only when they are prompted with BOS at the start of the sequence.

**Comment by BarfingLemurs** [comment]
@turboderp Thank you, disabling that in Parameter settings has fixed that.

**Comment by alkeryn** [comment]
@BarfingLemurs hey, what setting is it ? i cannot find it.
