### ISSUE TITLE
What is "an improved exllamav2 quant method"?

### ISSUE THREAD

**Issue by yamosin** [turboderp/exllamav2#236]
https://huggingface.co/DiscoResearch/DiscoLM-120b/discussions/2#6574d8389fe27c093d75b8ec

I've read about this on Reddit and hf, but the convert script for this repo doesn't mention it, is that because this is still experimental, or is it enough to just use the latest convert.py directly?

**Comment by turboderp** [comment]
The improved method changes the way quantization parameters are assigned to matrices. They're applied layer by layer now rather than matrix by matrix, which makes the error more predictable and produces more stable conversions. There is also a built-in calibration dataset now that you can use by not supplying one with `-c`. Which I recommend since it's designed to be very diverse and to reduce the risk of overfitting, especially with very low bitrates.

The experimental branch is closed and the changes are in the master branch now, so as long as you're on the latest version you should be good. Note that the new method isn't compatible with older measurement.json files.

**Comment by Simplegram** [comment]
> The improved method changes the way quantization parameters are assigned to matrices. They're applied layer by layer now rather than matrix by matrix, which makes the error more predictable and produces more stable conversions. There is also a built-in calibration dataset now that you can use by not supplying one with `-c`. Which I recommend since it's designed to be very diverse and to reduce the risk of overfitting, especially with very low bitrates.
> 
> The experimental branch is closed and the changes are in the master branch now, so as long as you're on the latest version you should be good. Note that the new method isn't compatible with older measurement.json files.

Hello, I have a question. So can I use the built-in dataset for all my exl2 quants? Would it make a difference to use one of the datasets used to train the model?
