### ISSUE TITLE
Conversion help

### ISSUE THREAD

**Issue by Chainfire** [turboderp/exllamav2#25]
Completely new at this, but to play around with exllamav2 and its new format, I'm trying to convert: 

https://huggingface.co/ehartford/Samantha-1.11-CodeLlama-34b/tree/main , using the parquet file from the llm-leaderboard.

`convert.py` complains:

```
Traceback (most recent call last):
  File "/home/jorrit/llama/exllamav2/convert.py", line 53, in <module>
    model.load(lazy = True)
  File "/home/jorrit/llama/exllamav2/exllamav2/model.py", line 227, in load
    stats = self.set_device_map(gpu_split or [99999])
  File "/home/jorrit/llama/exllamav2/exllamav2/model.py", line 185, in set_device_map
    footprint = module.weight_footprint()   # Footprint, in bytes
  File "/home/jorrit/llama/exllamav2/exllamav2/attn.py", line 109, in weight_footprint
    self.q_proj.weight_footprint() + \
  File "/home/jorrit/llama/exllamav2/exllamav2/module.py", line 118, in weight_footprint
    else: raise ValueError("Unknown tensor type: " + self.key)
ValueError: Unknown tensor type: model.layers.0.self_attn.q_proj
```

So I thought perhaps this needed to go through `convert_llama_weights_to_hf`, but that seems to be made to work specifically with the original llama files, which these obviously aren't. 

Am I barking up the wrong tree here? Should I get the 8-bit GPTQ files as source instead? Or is there just currently no way to convert a model such as this?

**Comment by turboderp** [comment]
I think at the moment there might not be an error message when it doesn't find any .safetensors files in the model directory. There probably should be. Instead it just creates an empty map of where to find the required tensors and gets confused when there's nothing available matching either FP16, GPTQ or EXL2.

In other words, I think the problem is you have the .bin file, not the .safetensors version.

**Comment by Thireus** [comment]
@turboderp, is there any chance we can have a bin2safetensors embedded within convert.py when it detects it's not safetensors?

**Comment by epicfilemcnulty** [comment]
@Thireus Since most of my downloaded weights are in pytorch format, I had to find a script to convert them, made a couple of modifications and here it is: https://gist.github.com/epicfilemcnulty/1f55fd96b08f8d4d6693293e37b4c55e

`Usage: python 2safetensors.py -m /model/dir -d True` -- this will create safetensors files in the model dir and remove pytorch weights after conversion. Remove `-d True` if you want to keep pytorch weights.

**Comment by Thireus** [comment]
Thank you so much @epicfilemcnulty!!!
