### ISSUE TITLE
It's using 19gb of vram for a 2.65bit 13b model

### ISSUE THREAD

**Issue by BadisG** [turboderp/exllamav2#3]
Something's wrong there 
https://huggingface.co/turboderp/CodeLlama-13B-instruct-2.65bpw-h6-exl2
![image](https://github.com/turboderp/exllamav2/assets/110173477/dc112d25-3bd8-40f5-ab59-27e3e3f74e38)

**Comment by turboderp** [comment]
If you run it without the `-l` argument it will default to the context size suggested by the model's `config.json` file, which in this case is 16k. Since there's no GQA for the 13B models, the cache ends up being huge at that size. With the context at 2048 tokens I'm measuring 7968 MiB all in all, with all the overhead from Torch and CUDA.

**Comment by BadisG** [comment]
Oh I see, thanks!
What's the equivalent to a act_order + groupsize 32 in your number of bits target? Something like 4.5 bps perhaps?

**Comment by turboderp** [comment]
4.625. The actual number of bits used by GPTQ is `(group_size * 4 + 4 + 16) / group_size`. An EXL2 model at 4.625 bits would be a little smaller still, since the head/output layer is quantized separately (to about 6.3 bits) where in GPTQ it's kept in FP16 precision.
