### ISSUE TITLE
Performance drops with longer prompts?

### ISSUE THREAD

**Issue by qss-uzair** [turboderp/exllamav2#356]
I'm running the `streaming.py` example on an NVidia Jetson Orin AGX, using some version of Mistral 7B. With the original prompt I get 31 t/s, but when I use a longer prompt (~1000 tokens), the performance degrades to 20 t/s.

Is it normal / expected?

**Comment by qss-uzair** [comment]
moreover, I found something unusual:
```
Prompt processed in 0.10 seconds, 1441 tokens, **14982.14 tokens/second**
Response generated in 14.85 seconds, 250 tokens, 16.83 tokens/second
````
I've tried replacing time.time() with time.perf_counter(), with the same result.

**Comment by turboderp** [comment]
It does actually look like there's a small bug in the streaming example. It needs a `torch.cuda.synchronize()` after `generator.begin_stream` to measure the prompt speed correctly. Otherwise the `begin_stream` function exits immediately after setting up the CUDA queue while there's still work to do, which would be incorrectly counted as latency for the first token.

Generation speed dropping with longer context is normal, though. There's simply more work to do the more context you have to attend to. Flash Attention mitigates this a bit. Not sure if you can run that on the Jetson.
