### ISSUE TITLE
Llava support?

### ISSUE THREAD

**Issue by kinchahoy** [turboderp/exllamav2#357]
Hey folks,

I'd love to try doing a fast quantization of a [LLaVA model](https://llava-vl.github.io/) or perhaps [MOE-LLaVA](https://github.com/PKU-YuanGroup/MoE-LLaVA). Will ExLlama work out of the box, or will I need to modify things?

I'm also interested in if exploring exllama's techniques can help with IQ1_S quantizations (currently all the rage thanks to the trinary paper). Right now going from 3 bit to 1.68 bit 4xs perplexity and the improved techniques here should help. Would love to chat with folks who might be looking at it.

**Comment by turboderp** [comment]
You'd need to implement CLIP, or rewrite ExLlamaV2 to integrate with Transformers. It's not something I currently have on the roadmap, but you're welcome to have a stab at it of course.

As for BitNet, it's not a quantization technique, it's a model architecture with binary/ternary quantization built in. As such it requires pretraining models from scratch, which costs millions of dollars. If they ever release the 3B model they mention in their paper it's probably worth adding support for in the hopes that larger models will appear in the future (and the architecture turns out to scale well enough). But until then it's not all that relevant.

**Comment by alkeryn** [comment]
@turboderp do you think it'd be possible to train a bitnet model to approximate a non bitnet model layer by layer ?

so for example take a llama model, and train some bitnet to approximate layer one then layer 2 etc.. until you got a crude approximation of the whole model.

doing it per layer is most definitely not as good as a full training on a dataset but maybe it could be not too terrible idk.

**Comment by turboderp** [comment]
Layer-wise distillation has been studied a bunch, and it's possibly worth pursuing for binarization. I would expect it to take quite a lot of compute for a large model, though. And ultimately it rests on the assumption that the FP16 hidden states are useful targets for the BitNet layers.

**Comment by aliencaocao** [comment]
On the same goal here - would it be possible to just input the embedding tensor from CLIP (in original fp16 HF impl) into exllamav2 running the llm part of llava?
