### ISSUE TITLE
publish the releases to github

### ISSUE THREAD

**Issue by happysalada** [turboderp/exllamav2#56]
can you publish the releases to github ?

**Comment by Nikita-Sherstnev** [comment]
Publishing package to pip or conda with precompiled extension would be also nice.

**Comment by turboderp** [comment]
There is a pip package already (`pip install exllamav2` works up to the latest commit with a version number). It looks like @jllllll already has a fork that allows permanently installing the extension, though there are no pre-built binaries yet. At some point I do plan to petition them to bring it all into the main repo, because especially the way they did it for V2 where the JIT compilation is still supported would be really nice to just have. I think the holdup is I just haven't familiarized myself with the workflows and whatever else is required to generate all the pre-built wheels with every release.

**Comment by jllllll** [comment]
I can open a PR that includes workflows, though I have no experience with pushing wheels to pypi automatically with them.

**Comment by turboderp** [comment]
That would be awesome. I doubt pushing wheels to PyPI could be much more involved than using twine.

**Comment by jllllll** [comment]
Doing some testing and I'm not sure how to go about uploading the pre-compiled wheels to PyPI without requiring that users specify the exact version to install: `pip install exllamav2==0.0.3+cu118`

pip will view any version tags like that as being a newer version and will consequently prefer to install that wheel unless explicitly told what wheel version to install.
