### ISSUE TITLE
Command R+ is broken?

### ISSUE THREAD

**Issue by Ph0rk0z** [turboderp/exllamav2#612]
I downloaded the new one and it would output garbage over and over. Figured it was the quant so I loaded the previous versions. All output repeating nonsense. Tried both textgen and tabbyAPI. Other models appear to work fine. Sometimes I got it to be coherent, but as soon as I tried any sampling it would irreparably break. Don't know who the offender is but tried dev and 0.1.9, happened to both.

built 0.1.8 and issue doesn't appear there.

**Comment by turboderp** [comment]
You need to be more specific. What platform, first of all? And do you have `fasttensors` enabled?

**Comment by Ph0rk0z** [comment]
I'm on linux with torch 2.4.0. I don't use fasttensors because my server caches model weights in ram and direct reading breaks it.

**Comment by turboderp** [comment]
I've seen some sporadic issues with Command-R specifically, but I was only able to reproduce them for a while, then the error spontaneously stopped happening and I'm still trying to trigger it again.

What I was able to determine is that it happens specifically for Command-R and specifically has something to do with tensor storage, since `fasttensors` reliably eliminated the error. My best guess right now is that safetensors does something radically different when loading to system RAM, as it will when loading the MLP up and gate tensors, since those are remapped in system RAM before being offloaded to the GPU.

I'm still trying to recreate the error so I can maybe try to figure out exactly where it's happening. I've had so many issues with the safetensors library, though, perhaps it's just time to drop it altogether. Idk.

**Comment by Ph0rk0z** [comment]
I updated to latest safetensors and in txgui it will output fine with low context. If I hit it with sillytavern API requests it's back to saying RaulRaulRaulRaul.

Getting rid of safetensors is fine as long as i'm not stuck with fasttensors, that's like loading the model first time, every time. I'll enable it and see if it at least gets rid of this behavior.

**Comment by turboderp** [comment]
Yep, on Linux, fasttensors is fast because it bypasses the OS cache, which is great if you have really fast storage but of course otherwise you just lose caching for no good reason. There are other approaches, of course, including a fallback mode I wrote just for Windows where safetensors has some other really annoying issues (with memory management). I could adapt that for Linux and you should get the best of both worlds.

It would be nice to narrow down the problem with Cohere first, though, to make sure it's actually limited to safetensors and not just some unrelated bug that happens to be exposed by something in safetensors.

**Comment by Ph0rk0z** [comment]
I tried cuda 12 and 11 and fast-tensors. no difference. 
![Raul](https://github.com/user-attachments/assets/cfaa4bb5-42b6-486e-94fd-24f9a2f1561b)

**Comment by turboderp** [comment]
I'd still need a lot more info to be able to reproduce the issue.

**Comment by Ph0rk0z** [comment]
I tried both latest TabbyAPI and exllama_hf in textgen. My settings are simply .9 temp and min_P of .03. It's on 3x3090 with flash_attn. Tried 4 and 8bit cache.

Exllama_HF is coherent in notebook mode on ooba, initially. API requests from sillytavern return as above and then the model breaks in ooba too. Once it calls upon the spirit of Raul, it remains on mescaline until reloaded.

Am using this quant: https://huggingface.co/BigHuggyD/c4ai-command-r-plus-08-2024_exl2_4.5bpw_h6 


Not sure what else to add.. *all* prompts do it. Downgrading to 0.1.8 and the exact same stack/prompt/model works.

**Comment by Ph0rk0z** [comment]
In TGUI I tried disabling the bos token and still get Raul through the API but in the UI itself I get different nonsense like 0s. It definitely wasn't this way in 0.1.8 because I used the model a lot. I was sorta hoping to try it in TP but some scratch buffer isn't supported. This seems like a slightly worse problem.

I was going to try to checkout before likely commits on 0.1.9 and try to narrow it down if it's indeed this hard to reproduce.

**Comment by Ph0rk0z** [comment]
The offending commit is: https://github.com/turboderp/exllamav2/commit/036506f27310153ddd35701013c87608eeb15e17

The one before works. All after call on Raul. Sampling didn't have anything to do with it, you can turn off do_sample.

**Comment by turboderp** [comment]
I don't have a Windows PC that can run this model, but apparently on Linux there's an issue with safetensors. Enabling `fasttensors` fixes it here.

**Comment by Ph0rk0z** [comment]
Enabling fast tensors does not fix it for me and I am on linux. The commit before "Use high priority stream for forward pass" works perfectly no matter how I load it.

**Comment by Inktomi93** [comment]
> Okay, so I _think_ I tracked this down now. It's specific to Tabby because of the way it spawns threads to serve requests. Some state in Torch is thread-local, which could cause ExLlama to use the wrong CUDA streams under specific conditions, causing tensors to end up being moved between devices prematurely.
> 
> Anyway, I've pushed a commit to the dev branch that hopefully fixes it. Before:
> 
> ```json
>   "choices": [
>     {
>       "index": 0,
>       "finish_reason": "length",
>       "stop_str": null,
>       "message": {
>         "role": "assistant",
>         "content": "RâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâul小行星RâulRâulRâulRâulRâulRâul小行星RâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâul小行星RâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâulRâul",
>         "tool_calls": null
>       },
>       "logprobs": null
>     }
>   ],
> ```
> 
> After:
> 
> ```json
>   "choices": [
>     {
>       "index": 0,
>       "finish_reason": "length",
>       "stop_str": null,
>       "message": {
>         "role": "assistant",
>         "content": "Raul is a name typically used for males, and it is of Spanish origin. Raul means \"wolf\". The meaning of Raul is \"wolf council\". It is derived from the Hispanicized form of Raoul, a French name that means \"wild counsel\". \n\nRegarding where you can find Raul, it depends on the specific Raul you are looking for. There may be many people named Raul in the world, and their location would depend on their specific circumstances. Some ways to potentially find someone include:",
>         "tool_calls": null
>       },
>       "logprobs": null
>     }
>   ],
> ```

So far, in my testing, it works, at least on Tabby.

**Comment by Ph0rk0z** [comment]
Thanks! It's working here in both textgen and tabby. No more raul.
