### ISSUE TITLE
linear growth in system RAM during load change in v0.1.8 to v0.2

### ISSUE THREAD

**Issue by edk208** [turboderp/exllamav2#618]
First of all, thanks for all your work.  Hoping you might be able to point me to a change made between release v0.1.8 and v0.2.  I'm seeing a change in the system RAM usage during model loading that I'm trying to track down where the system RAM was hardly used during model load, but in v0.2 seems to grow linearly over model load time.  It does not seem to be a PP vs TP issue as loading both pipelines has the same effect.  If you could point me to the relevant change, that would be great thanks!

**Comment by edk208** [comment]
Ok nvm I found it, it's this commit https://github.com/turboderp/exllamav2/commit/d3fe9f25d2f1955a19b5f3015d50e5872a55cf1e

**Comment by Thireus** [comment]
This change is problematic for me as I have minimal RAM allocation on wsl (5GB of RAM), but this change forces me to have free RAM as large as the model VRAM required by the model which is huge on large models (e.g. 48GB of RAM). Would be great if this change could be behind an optional load parameter - @turboderp

**Comment by turboderp** [comment]
The loader only needs to keep one tensor in system RAM at a time. There are many issues with the safetensors library, though. Most of them are on Windows, but occasionally they manifest on Linux as well depending on virtual memory settings.

I would first of all update to v0.2.2 since there have been some bugs in the loader addressed since 0.2.0. Also try enabling fasttensors by setting `config.fasttensors = True` or defining the `EXLLAMA_FASTTENSORS` env variable, which should bypass safetensors. This is what loading a large model *should* look like:

![image](https://github.com/user-attachments/assets/94b31630-d810-4f46-87c0-b08a65c36896)

I'll be rewriting the whole loader, though, and removing safetensors as a dependency since it causes way too many issues.
