### ISSUE TITLE
[BUG] chat-instruct Llama 3.1 end word "assistant "

### ISSUE THREAD

**Issue by Katehuuh** [turboderp/exllamav2#632]
### OS

Windows

### GPU Library

CUDA 12.x

### Python version

3.10

### Pytorch version

3.10.8

### Model

turboderp/Llama-3.1-8B-Instruct-exl2

### Describe the bug

I always receive `assistant` at the end of each sentence.

![image](https://github.com/user-attachments/assets/2f6d32c7-9d2d-4d1f-9abf-89d950e930c3)

The bug only occurs with  Llama-3.1 family. The following models were tested:

- [turboderpLlama-3.1-8B-Instruct-exl2_8.0bpw](https://huggingface.co/turboderp/Llama-3.1-8B-Instruct-exl2/tree/8.0bpw) 
- [bullerwins/Meta-Llama-3.1-8B-Instruct-exl2_8.0bpw](https://huggingface.co/bullerwins/Meta-Llama-3.1-8B-Instruct-exl2_8.0bpw)

I am using [oobabooga/text-gen](https://github.com/oobabooga/text-generation-webui), and the issue only occurs in **chat-instruct** mode (the `chat` mode works correctly).

```cmd
INFO     Loading "bartowski_Meta-Llama-3.1-8B-Instruct-exl2_8_0"
INFO     Loaded "bartowski_Meta-Llama-3.1-8B-Instruct-exl2_8_0" in 18.84 seconds.
INFO     LOADER: "ExLlamav2"
INFO     TRUNCATION LENGTH: 131072
INFO     INSTRUCTION TEMPLATE: "Custom (obtained from model metadata)"
```

This also happens with the `Llama-v3` and Instruction template. The model loader `ExLlamav2_HF` and `Transformers` work correctly.

### Reproduction steps

To clarify, using the official [meta-llama/Meta-Llama-3.1-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct) with **ExLlamav2** as the loader causes the issue.

### Expected behavior

.

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by turboderp** [comment]
This is likely an instruct template issue. Not sure how the TGW loader works with templates, but probably you can fix it by modifying the config.json to only list token 128009 under "eos_token_id".

**Comment by Katehuuh** [comment]
> This is likely an instruct template issue. Not sure how the TGW loader works with templates, but probably you can fix it by modifying the config.json to only list token 128009 under "eos_token_id".

ur exl2 and Official [meta-llama/Meta-Llama-3.1-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct) does already have [128009 under "eos_token_id"](https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/blob/main/config.json#L11):
```json
    "eos_token_id": [
        128001,
        128008,
        128009
    ],
```

**Comment by Katehuuh** [comment]
@turboderp by remove `eos_token_id`: `128008` and `128009`, will it cause further issues?

**Comment by turboderp** [comment]
It's really up to the frontend to specify what the stop conditions are, as part of the instruct template. But because HF has a very confused format, these conflicts occur every now and again. ExLlama has a single token which is used as a default stop condition, so it doesn't really know what to do with models that decided they wanted multiple stop tokens all of a sudden. The frontend can still set as many stop conditions as it likes, though, to suit whatever instruct format it decides to use.

Switching to 128009 works for Llama3 specifically because that token marks the end of model responses in the L3 instruct template, and some frontends assume that a) model responses are supposed to end with EOS and b) models only define a single EOS token. Making matters a little more complicated, L3 had some errors in its config when it first launched (defining `<|end_of_text|>` in tokenizer_config.json instead of `<|eot_id|>` etc., and even as the models have been updated those changes aren't always reflected in the many quantized versions already on HF.
