### ISSUE TITLE
AntiSlop / banned strings

### ISSUE THREAD

**Issue by sam-paech** [turboderp/exllamav2#650]
### Problem

Hi, sorry for abusing your issues reporting, just want to get in touch with turboderp as I couldn't find another way to contact.

I made this antislop sampler: https://github.com/sam-paech/antislop-sampler

Didn't realise this method already existed more or less in exllama since May. It seems to be an under-utilised feature! Anyhow, I'm looking into writing a paper on this technique since I think it's quite powerful. Was wondering if you are interested in being involved?

Feel free to dm me on twitter: https://x.com/sam_paech

### Solution

See description

### Explanation

See description

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by turboderp** [comment]
I mean there's really not much to it. It's just comparing the output against a list of strings, and then rewinding if a banned string is encountered, masking out the token that caused the generator to go down that path and resampling at that position. Since the generator has a mechanism for holding output already (used for dealing with multi-token characters and stop strings), you can also hold any output that partially matches a banned string until the match is resolved. But the technical implementation isn't terribly exciting in any case. The core of the implementation is a simple multi string matching function [here](https://github.com/turboderp/exllamav2/blob/03b2d551b2a3a398807199456737859eb34c9f9c/exllamav2/exllamav2_ext/cpp/generator.cpp#L12), and the rest is just [some checkpointing logic](https://github.com/turboderp/exllamav2/blob/03b2d551b2a3a398807199456737859eb34c9f9c/exllamav2/generator/dynamic.py#L2065) in Python.

What I've found is that it's effective in some cases as a way to decensor models depending on how they've been censored. For instance, models that are tuned to *always* respond with very specific phrases ("As an AI language model..." etc.) in response to certain types of input usually don't have any redundancy. I.e. the original uncensored distribution still remains, just with the refusal phrase added with a heavy weight, so cutting that path off and renormalizing pretty much restores the uncensored model.

As for slop, the technique works for overfit models in general for the same reason. There are traps they like to fall into, and you can patch over those holes with this technique, once you identify them. Of course it's a bit of a kludge, and really the better solution is to use base models where appropriate, or at least not assume that what makes modern models better on benchmarks has anything to do with creativity, variety or expressiveness.

I don't know how much I'd have to contribute to a paper on the subject, but I've followed you on Twitter so feel free to DM if you have any ideas for what I might add..?
