### ISSUE TITLE
[REQUEST] LLama3.2 Vison Support

### ISSUE THREAD

**Issue by royallavanya140** [turboderp/exllamav2#687]
### Problem

I started using Pixtral with Exllama but want to verify it with Llama 3.2 Vision too.

### Solution

supporting llama3.2 vision

### Explanation

![image](https://github.com/user-attachments/assets/fc75651d-1bf0-423b-b5fe-2ce7f333ae81)

### Acknowledgements

- [X] I have looked for similar requests before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will make my requests politely.

**Comment by turboderp** [comment]
Llama3.2-Vision (Mllama) is a big departure from regular Llama, as unlike Pixtral, Qwen, Llava, Molmo and so many other VLMs it uses cross-attention layers rather than image feature embeddings for the extra modalities. Here are the main obstacles:

- Lots of extra code for the new xattn layers
- No obvious way (?) to format contexts with multiple images, or multiple chat turns with different images
- Llama3.2 doesn't seem to be performing any better than those other models anyway

Overall it is a low priority. Qwen2-VL is available in the dev branch, soon in the v0.2.5 release. It has a 72B version if it's more parameters you seek, and it supports grounding which is super neat. Also video support, although that may not be ready for the release. Either way, *probably* Molmo (D) is next, since it, too, looks to be more powerful than Llama3.2 and also wouldn't require any sweeping changes to the codebase. Not sure where L3.2 is on the list, to be honest.

**Comment by royallavanya140** [comment]
Thanks, bro @turboderp! Could you recommend a good configuration that can handle 50+ concurrent calls while maintaining the same inference speed? I’ve noticed that as the number of simultaneous calls increases, the generation speed drops. Would appreciate your suggestions! 😊

**Comment by DocShotgun** [comment]
> Could you recommend a good configuration that can handle 50+ concurrent calls while maintaining the same inference speed? I’ve noticed that as the number of simultaneous calls increases, the generation speed drops. Would appreciate your suggestions! 😊

If you purchase 50+ machines with your current hardware configuration, it would handle 50+ concurrent calls with the same inference speed.

**Comment by turboderp** [comment]
There's no way to process 50 requests in the same amount of time as you can process 1 request, unless you spread it across multiple GPUs. You can batch requests together, and while ExLlama's kernels aren't the best for medium batch sizes, they work very well at low and very high batch sizes. So for either a couple of concurrent requests, or for 50+, you should get close to the maximum performance the hardware allows, using memory-bound kernels or NVIDIA's optimized-to-death cuBLAS kernels, respectively.

But very high batch sizes, especially if you're doing image processing, will need a lot of VRAM for cache and activations, too.

**Comment by royallavanya140** [comment]
Thanks man @turboderp
