### ISSUE TITLE
[BUG] CUDA error: invalid configuration argument /exllamav2/exllamav2/exllamav2_ext/cuda/rope.cu 131

### ISSUE THREAD

**Issue by Facico** [turboderp/exllamav2#97]
Thanks for this excellent work!

When using lora (reproduced in example/lora.py in the repository), the author's 7b configuration works successfully. When I change to 70b, I get the following error "CUDA error: invalid configuration argument /exllamav2/exllamav2/exllamav2_ext/cuda/rope.cu 131 "

This problem only occurs when using streaming=False!

Additionally, there is a memory leak when GPU is not specified (CUDA_VISIBLE_DEVICES)  => other GPUs are about 900M each

**Comment by Ph0rk0z** [comment]
I have this problem when passing lora to the forward function.

**Comment by turboderp** [comment]
Do you have a link to a 70B LoRA that causes this?

**Comment by Ph0rk0z** [comment]
I tried a bunch over exl2 and gptq models, try https://huggingface.co/jondurbin/airoboros-l2-70b-2.2-checkpoints/tree/main/checkpoint-1000/adapter_model

**Comment by turboderp** [comment]
Yep, so there was a bug for large LoRAs. Miscalculated the size of the launch grid so it would try to launch too many threads. It should correctly fall back on cuBLAS for 70B LoRAs now. I'm not sure about the performance but I will be optimizing that at some point.

Also the streaming generator was just ignoring the LoRA altogether. Both issues should be fixed with the latest commit.

**Comment by turboderp** [comment]
The memory leak was due to the test in compat.py creating an entire CUDA context to test if peer access is supported. I limited it to only testing for devices actually being used, so that should be taken care of also.

**Comment by Ph0rk0z** [comment]
Can confirm it is resolved. I can use lora for 70b.

**Comment by Facico** [comment]
Thanks!
